Add UI for transaction on EVM
portto/wallet-web-ui pull request #13
Opened 2023-01-05 07:02 UTC by moojing

## Summary

- Add UI for transaction on EVM
## The parts will be implemented in later Pull Requests

## Related Links

**Asana**:  

**Mockup**:  https://www.figma.com/file/X8Jx6GxcEB9gxoMxujdDSD/7.-Wallet-Web-2.0?node-id=135%3A18586&t=aY5ZD9d0hggOsL74-1

## Checklist

- [x] Pasted Asana or Mockup link.
- [x] Tagged labels.

## Prerequisite/Related Pull Requests

## Screenshot/Gif

 
![Screenshot 2023-01-05 at 2 54 45 PM](https://user-images.githubusercontent.com/11360957/210720194-4a4c12f9-e07c-480a-94ce-6e84cd8cede5.png)
![Screenshot 2023-01-05 at 2 54 30 PM](https://user-images.githubusercontent.com/11360957/210720199-a7f4fe59-142e-4d38-ade5-2e1e03ffad1e.png)

2023-01-06 05:40 UTC, yanglin5689446 requested changes

2023-01-06 05:40 UTC, yanglin5689446 commented on src/features/EVM/Transaction/components/Main.tsx
> +                  &nbsp;(<Box as="del">{transaction.fee} Points</Box>)
please don't use `&nbsp;` as it's not easily readable, use padding or margin to add space

2023-01-06 08:55 UTC, mordochi reviewed
<img width="512" alt="截圖 2023-01-06 下午4 17 36" src="https://user-images.githubusercontent.com/32261044/210966413-c5652705-ba03-4626-b39c-cb7e469d77d3.png">

2023-01-06 08:55 UTC, mordochi commented on src/features/EVM/Transaction/components/Main.tsx
> +              p="4px"
design token

2023-01-06 08:55 UTC, mordochi commented on src/features/EVM/Transaction/components/Main.tsx
> +      <Box px="20px">
design token

2023-01-06 08:55 UTC, mordochi commented on src/features/EVM/Transaction/components/Main.tsx
> +      {/* <Box>Dapp</Box>
Should we remove this?

2023-01-06 08:55 UTC, mordochi commented on src/features/EVM/Transaction/components/Main.tsx
> +      <Flex justify="center" p="20px" pos="absolute" bottom="0" width="100%">
`p="space.l"`

2023-01-06 08:55 UTC, mordochi commented on src/features/EVM/Transaction/components/Main.tsx
>      <Box fontSize={10}>
Guess we can remove this `fontSize={10}`

2023-01-06 08:55 UTC, mordochi commented on src/features/EVM/Transaction/components/messages.js
> +import { defineMessages } from "react-intl";
Please update the translation files too. Thanks

2023-01-06 08:55 UTC, mordochi commented on src/features/EVM/Transaction/components/TransactionContent.tsx
> +      <Box mt="24px" wordBreak="break-all" fontSize="size.body.3">
design token

2023-01-06 09:00 UTC, mordochi commented on src/features/EVM/Transaction/components/Main.tsx
> +                  &nbsp;(<Box as="del">{transaction.fee} Points</Box>)
Also use translation string for this

2023-01-06 09:07 UTC, mordochi commented
Could you confirm with Dori for the UI of transferring on EVM?
Maybe we should display other information in `TransactionContent` since there's no transaction data.

<img width="474" alt="截圖 2023-01-06 下午4 16 01" src="https://user-images.githubusercontent.com/32261044/210967950-974f0c9a-c23e-4b46-86a7-bb59b8cf0c69.png">
<img width="653" alt="截圖 2023-01-06 下午4 16 36" src="https://user-images.githubusercontent.com/32261044/210967952-a7951385-06e4-446c-a8a1-f24294f4f625.png">

2023-01-06 09:19 UTC, moojing commented on src/features/EVM/Transaction/components/Main.tsx
> +      {/* <Box>Dapp</Box>
this will be removed later after the whole tx view is finished.

2023-01-06 09:21 UTC, mordochi commented on src/features/EVM/Transaction/components/Main.tsx
> +      {/* <Box>Dapp</Box>
Got it

2023-01-07 16:37 UTC, moojing commented on src/features/EVM/Transaction/components/TransactionContent.tsx
> +      <Box mt="24px" wordBreak="break-all" fontSize="size.body.3">
fix here https://github.com/portto/wallet-web-ui/pull/13/commits/22e22297568abeb7d4d519f148aba2f8ec2c399f
and it seems the design token value doesn't work with  `borderRadius`'s `radius.m`

2023-01-07 16:39 UTC, moojing commented on src/features/EVM/Transaction/components/TransactionInfo.tsx
> +        interacting
OK, https://github.com/portto/wallet-web-ui/pull/13/commits/38d408b6fbf6bb0f297b4257875f1189885664f9#diff-0bbf0bab3ebef9bf07b4a6cc67b7d79f94b550bfcad8e34e885c404eed9a562aL15

2023-01-07 16:40 UTC, moojing commented on src/features/EVM/Transaction/components/Main.tsx
>          <Button onClick={approve}>Approve</Button>
fix here, thx!
https://github.com/portto/wallet-web-ui/commit/38d408b6fbf6bb0f297b4257875f1189885664f9#diff-fd263647b1177aa9d7e35c9ff8592cab5b463a9d14eb1ab0eea74c527288c246R211-R213

2023-01-07 16:40 UTC, moojing commented on src/features/EVM/Transaction/components/Main.tsx
>      <Box fontSize={10}>
removed, thx!
https://github.com/portto/wallet-web-ui/commit/38d408b6fbf6bb0f297b4257875f1189885664f9#diff-fd263647b1177aa9d7e35c9ff8592cab5b463a9d14eb1ab0eea74c527288c246L126

2023-01-07 16:42 UTC, moojing commented on src/features/EVM/Transaction/components/Main.tsx
> +      <Flex justify="center" p="20px" pos="absolute" bottom="0" width="100%">
sure.
https://github.com/portto/wallet-web-ui/commit/38d408b6fbf6bb0f297b4257875f1189885664f9#diff-fd263647b1177aa9d7e35c9ff8592cab5b463a9d14eb1ab0eea74c527288c246R210

2023-01-07 16:43 UTC, moojing commented on src/features/EVM/Transaction/components/Main.tsx
> +      <Box px="20px">
here!
https://github.com/portto/wallet-web-ui/commit/38d408b6fbf6bb0f297b4257875f1189885664f9#diff-fd263647b1177aa9d7e35c9ff8592cab5b463a9d14eb1ab0eea74c527288c246R142

2023-01-07 16:44 UTC, moojing commented on src/features/EVM/Transaction/components/Main.tsx
> +              p="4px"
ok~
https://github.com/portto/wallet-web-ui/commit/38d408b6fbf6bb0f297b4257875f1189885664f9#diff-fd263647b1177aa9d7e35c9ff8592cab5b463a9d14eb1ab0eea74c527288c246R103

2023-01-07 16:47 UTC, moojing commented on src/features/EVM/Transaction/components/Main.tsx
> +                  &nbsp;(<Box as="del">{transaction.fee} Points</Box>)
all updated [here](https://github.com/portto/wallet-web-ui/pull/13/commits/4b07c569aa3c758ff75d8333a0d1b301337f7790#diff-fd263647b1177aa9d7e35c9ff8592cab5b463a9d14eb1ab0eea74c527288c246R112-R114)

2023-01-09 04:20 UTC, mordochi commented on src/features/EVM/Transaction/components/TransactionContent.tsx
> +      <Box mt="24px" wordBreak="break-all" fontSize="size.body.3">
Yeah it's something that we haven't done so far. Because it'll be quite a hassle to deal with building the tokens differently for the brder-radius token. Also, there's only one alias token related to it so I just skip this for now :P

2023-01-09 04:21 UTC, mordochi commented on src/features/EVM/Transaction/components/TransactionContent.tsx
> +      <Box mt="24px" wordBreak="break-all" fontSize="size.body.3">
BTW you miss `fontWeight="600"` on line 17 XD

2023-01-09 04:30 UTC, mordochi commented on src/features/EVM/Transaction/components/TransactionInfo.tsx
> +        interacting
Not sure whether we should confirm the wording since it's different from the Figma, though I know it's the wording from the current SDK.
Also, I find there're different strings for tx info, `Interacting wiith`, `Interacting` and `Confirm transaction with` 🤔

2023-01-09 05:29 UTC, yanglin5689446 approved these changes

2023-01-09 06:13 UTC, moojing commented on src/features/EVM/Transaction/components/TransactionInfo.tsx
> +        interacting
I agree with you, and I've ask Dori for help this morning, let's wait for her response.

2023-01-10 04:46 UTC, moojing commented on src/features/EVM/Transaction/components/TransactionContent.tsx
> +      <Box mt="24px" wordBreak="break-all" fontSize="size.body.3">
okok, changed [here](https://github.com/portto/wallet-web-ui/pull/13/commits/607376b930e7c19cf7d4523531423fd1e8f32253#diff-2ccc2cb4bda5ea63a6f36a70a095271a4f5297cd64ec4feab61db1de22508084R20)

2023-01-10 04:52 UTC, moojing commented
> Could you confirm with Dori for the UI of transferring on EVM? Maybe we should display other information in `TransactionContent` since there's no transaction data.

After confirming with Dori, there should be no arrow when transferring on EVM,and I plan to handle this in the next PR, so let me keep it like this now.

2023-01-10 05:12 UTC, moojing commented on src/features/EVM/Transaction/components/TransactionInfo.tsx
> +        interacting
The designer decide to make the sting to be `Confirm transaction from`, so I ended up adding a new string for a better expression of the string name and keep the old  `interactingWith` for now.

2023-01-10 18:04 UTC, mordochi approved these changes

2023-01-12 04:12 UTC, merged